from app.core.provider_crypto import decrypt_provider_secret
from app.repositories.agent import (
    create_agent_run,
    find_agent_run_by_id,
    find_agent_session_by_id,
    find_user_setting,
    list_runs_for_session,
    update_agent_run,
    update_agent_session,
)
from app.repositories.providers import find_active_provider_for_user
from app.schemas.agent import AgentRunToolExecutionDto
from app.services.agent._confirmations import (
    confirm_agent_tool_record,
    reject_agent_tool_record,
    stream_confirm_agent_tool_record,
    stream_reject_agent_tool_record,
)
from app.services.agent._constants import (
    PENDING_CONFIRMATION_TOOL_ID,
    PENDING_CONFIRMATION_TOOL_NAME,
    SUPPORTED_STREAM_PROVIDER_FORMATS,
    AgentModelRuntimeConfig,
    AgentToolCall,
)
from app.services.agent._execution import stream_agent_run_record
from app.services.agent._provider import (
    _extract_anthropic_stream_delta_text,
    _extract_gemini_stream_delta_text,
    _extract_stream_delta_text,
    _stream_anthropic_messages,
    _stream_gemini_generate_content,
    _stream_openai_chat_completion,
    _stream_provider_chat_completion,
)
from app.services.agent._runs import (
    create_agent_run_record,
    delete_agent_run_record,
    get_agent_run_detail,
    get_agent_run_list,
    update_agent_run_record,
)
from app.services.agent._sessions import (
    create_agent_session_record,
    delete_agent_session_memory_record,
    delete_agent_session_record,
    get_agent_capabilities,
    get_agent_persona,
    get_agent_runtime_status,
    get_agent_session_detail,
    get_agent_session_list,
    get_agent_session_memory_record,
    update_agent_persona_record,
    update_agent_session_memory_settings_record,
    update_agent_session_record,
)
from app.services.agent._state import (
    _build_pending_confirmation_tool,
    _build_run_detail_from_state,
    _to_agent_run_detail,
)
from app.services.agent._tools import (
    _build_effective_system_prompt,
    _execute_agent_tool_call,
    _execute_pending_confirmation_tool,
    _parse_tool_calls,
    _supported_agent_tool_names,
)

__all__ = [
    "AgentModelRuntimeConfig",
    "AgentRunToolExecutionDto",
    "AgentToolCall",
    "PENDING_CONFIRMATION_TOOL_ID",
    "PENDING_CONFIRMATION_TOOL_NAME",
    "SUPPORTED_STREAM_PROVIDER_FORMATS",
    "_build_effective_system_prompt",
    "_build_pending_confirmation_tool",
    "_build_run_detail_from_state",
    "_execute_agent_tool_call",
    "_execute_pending_confirmation_tool",
    "_extract_anthropic_stream_delta_text",
    "_extract_gemini_stream_delta_text",
    "_extract_stream_delta_text",
    "_parse_tool_calls",
    "_stream_anthropic_messages",
    "_stream_gemini_generate_content",
    "_stream_openai_chat_completion",
    "_stream_provider_chat_completion",
    "_supported_agent_tool_names",
    "_to_agent_run_detail",
    "confirm_agent_tool_record",
    "create_agent_run",
    "create_agent_run_record",
    "create_agent_session_record",
    "decrypt_provider_secret",
    "delete_agent_run_record",
    "delete_agent_session_memory_record",
    "delete_agent_session_record",
    "find_active_provider_for_user",
    "find_agent_run_by_id",
    "find_agent_session_by_id",
    "find_user_setting",
    "get_agent_capabilities",
    "get_agent_persona",
    "get_agent_run_detail",
    "get_agent_run_list",
    "get_agent_runtime_status",
    "get_agent_session_detail",
    "get_agent_session_list",
    "get_agent_session_memory_record",
    "list_runs_for_session",
    "reject_agent_tool_record",
    "stream_agent_run_record",
    "stream_confirm_agent_tool_record",
    "stream_reject_agent_tool_record",
    "update_agent_persona_record",
    "update_agent_run",
    "update_agent_run_record",
    "update_agent_session",
    "update_agent_session_memory_settings_record",
    "update_agent_session_record",
]
